---
title: "Comparison of diagnoses generated by MCAS criteria"
output: html_notebook
---

```{r}
library(tidyverse)
library(iNEXT)
library(vegan)
source(here("util_functions.R"))
```

# Reading data

```{r}
parse_diagnoses <- function(sim_results, consensus){
  sim_results <- do.call(rbind, sim_results[consensus, ])
  map(sim_results$diagnoses, process_diagnoses) %>% 
    enframe(name = "iteration", value = "diagnosis") %>% 
    unnest(diagnosis) %>% 
    mutate(consensus = consensus)
}

parse_rds <- function(sim_results){
  bind_rows(
    parse_diagnoses(sim_results, "consensus1"),
    parse_diagnoses(sim_results, "consensus2")
  )
}
  
plot_diagnosis <- function(df, c, n_diagnoses=25) {
  df %>% 
    filter(consensus == c) %>% 
    count(diagnosis, sort = T) %>% 
    mutate(freq = n/sum(n)) %>% 
    top_n(n_diagnoses, n) %>%
    mutate(diagnosis = fct_reorder(diagnosis, n)) %>% 
    ggplot(aes(x = diagnosis, y = freq))+
    geom_bar(stat = "identity")+
    theme_bw() +
    coord_flip() +
    labs(x="", y="Frequency") +
    theme(axis.text.x = element_text(angle = 90))
}
```

```{r}
# Read in chatGPT output
# n2000 directory contains data from 20,000 chatGPT iterations
df <- tibble(file = list.files(here("data/chatgpt_output/name_n20000"), full.names = T)) %>% 
  filter(grepl("RDS$", file)) %>% 
  mutate(data = map(file, readRDS)) %>% 
  mutate(data = map(data, parse_rds)) %>% 
  unnest(data) %>% 
  select(-file, -iteration)
df
```
```{r, message=F}
# write_csv(df, here("data/compiled_mcas_chatgpt_diagnoses.csv"))
df <- read_csv(here("data/compiled_mcas_chatgpt_diagnoses.csv"))
```

# Top diagnoses

```{r}
# Top n diagnoses plots
plot_top25 <- cowplot::plot_grid(
  plot_diagnosis(df, c="consensus1", n_diagnoses = 25)+ggtitle("Consortium") + ylim(0,0.1),
  plot_diagnosis(df, c="consensus2", n_diagnoses = 25)+ggtitle("Alternative") + ylim(0,0.1),
  nrow = 1,
  rel_widths = c(0.45,0.5)
)
plot_top25
```

```{r}
# Get the individual proportions of top 5 diagnoses
df %>% 
  count(consensus, diagnosis) %>% 
  group_by(consensus) %>% 
  mutate(freq = n/sum(n)) %>% 
  slice_max(order_by = n, n = 5)
```


```{r}
# Get cumulative proportion of top 30 diagnoses
df %>% 
  count(consensus, diagnosis) %>% 
  group_by(consensus) %>% 
  mutate(freq = n/sum(n)) %>% 
  slice_max(order_by = n, n = 25) %>% 
  summarise(top_f = sum(freq), top_n = sum(n))
  
```


```{r}
# Rank abundance plot
df_cs <- df %>% 
  count(consensus, diagnosis) %>% 
  group_by(consensus) %>% 
  mutate(freq = n/sum(n)) %>% 
  arrange(desc(freq), .by_group = T) %>% 
  mutate(rank = 1:n()) %>% 
  select(consensus, freq, rank) %>% 
  # filter(rank <= 500) %>% 
  mutate(cs = cumsum(freq))

df_cs %>% 
  filter(rank <= 100) %>% 
  mutate(consensus = ifelse(consensus == "consensus1", "Consensus-1", "Consensus-2")) %>% 
  ggplot(aes(x = rank, y = freq, color = factor(consensus)))+
    geom_line() +
    theme_classic()+
    scale_color_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Diagnosis rank", y = "Diagnosis frequency", color = "")
```
```{r}
consolidate_diagnoses <- function(df, pattern){
  df <- df %>% 
    group_by(consensus, diagnosis) %>% 
    tally() %>% 
    arrange(consensus, desc(n)) %>% 
    mutate(rank = 1:n()) %>% 
    group_by(consensus) %>% 
    mutate(freq = n/sum(n)) 
    
  df_filter <- df %>% 
    filter(grepl(pattern, diagnosis))
  
  pattern_match <- paste(df_filter$diagnosis, collapse = ", ")
  
  pattern_ranks <- df_filter %>% 
    group_by(consensus) %>% 
    summarise(rank = paste(rank, collapse = ", ")) %>% 
    deframe()
  
  pattern_freq <- df_filter %>% 
    group_by(consensus) %>% 
    summarise(freq = sum(freq)) %>% 
    deframe()
  
  adjusted_rank <- df %>% 
    left_join(enframe(pattern_freq, "consensus"), by = "consensus") %>% 
    filter(freq >= value) %>% 
    group_by(consensus) %>% 
    summarize(rank = max(rank)) %>% 
    deframe()
  
  list(
    "pattern" = pattern,
    "pattern_match" = pattern_match,
    "pattern_ranks" = pattern_ranks,
    "pattern_freq" = pattern_freq,
    "adjusted_rank" = adjusted_rank
  )
}

consolidate_diagnoses(df, "mast cell")
consolidate_diagnoses(df, "mastocytosis")
```

# Diversity

### Shannon entropy
```{r}
diagnosis_table <- table(df$consensus, df$diagnosis)
div_diag  <- vegan::diversity(diagnosis_table)
div_diag  
```

### Renyi entropy curves

```{r}
vegan::renyi(table(df$consensus, df$diagnosis), scales = seq(from=0,to=2,by=0.1)) %>%
  rownames_to_column("consensus") %>% 
  pivot_longer(-consensus, names_to = "order", values_to = "renyi") %>% 
  ggplot(aes(x=as.numeric(order), y=renyi, color = consensus))+
  geom_line() +
  theme_classic()+
  scale_color_brewer(palette = "Set1")
```

### iNEXT extrapolation

```{r, eval = F}
# Contained in "/scripts/mcas_iNEXT_calculation.R"
f_cs <- df %>% 
  count(consensus, diagnosis) %>% 
  pivot_wider(names_from = "consensus", values_from = n, values_fill = 0) %>% 
  column_to_rownames("diagnosis")

e <- 500000 # Sets how many diagnoses to sample to
iNEXT_out <- iNEXT(df_cs, q=c(0, 1, 2), datatype="abundance", endpoint = e)

# saveRDS(iNEXT_out, here(sprintf("data/mcas_iNEXT_e%s.RDS", format(e, scientific = F))))
```


```{r}
mcas_iNEXT <- readRDS(here("data/mcas_iNEXT_e500000.RDS"))
```

```{r, fig.width = 8, fig.height = 4}
for (i in 1:3){
  plt <- ggiNEXT(mcas_iNEXT, type=i, facet.var="Assemblage", color.var="Assemblage") +
    theme_classic() + 
    scale_color_brewer(palette = "Set1")
  print(plt)
}
```
```{r}
mcas_iNEXT$iNextEst$coverage_based %>% 
  filter(SC >=0.989 & SC <= 0.992) %>% 
  filter(Order.q == 0) 
```

### Permutation testing

```{r}
permutation_pair_iteration <- function(randomize = T){
  if (randomize == T){
    df <- df %>% mutate(diagnosis = sample(diagnosis, n()))
  }
  div <- vegan::diversity(table(df$consensus, df$diagnosis))
  unname(div[1] - div[2])
}

# Shannon entropy difference when diagnoses randomized
permutation_pair_iteration() 

# Shannon entropy difference with original consensus-diagnosis associations
permutation_pair_iteration(randomize = F)  
```
```{r, eval = F}
# Contained in /scripts/generate_mcas_criteria_null_distribution.R
set.seed(1234)
div_rep <- replicate(10000, permutation_pair_iteration())
```


```{r}
div_rep <- readRDS(here("data/mcas_criteria_null_distribtion.RDS"))
```


```{r}
# Plot null sampling distribution with actual entropy difference in red
ggplot(data = data.frame(entropy_difference = div_rep), aes(x = entropy_difference, y = ..density..))+
  geom_histogram(binwidth = 0.01, color = "black", fill = "grey50") +
  geom_density()+
  theme_classic() +
  geom_vline(aes(xintercept = permutation_pair_iteration(randomize = F)), color = "red")+
  ylim(0,NA)

```

# Figures

```{r}
points_to_inches <- function(points){
  # Single column - 255 pts
  # 1.5 column - 397 pts
  # Two column - 539 pts
  points/72
}
points_to_inches(255)
points_to_inches(539)
```

```{r, fig.width=7.4, fig.height=4}
plt_top_25 <- df %>%
  mutate(consensus = factor(ifelse(consensus == "consensus1", "Consortium", "Alternative"), 
                            levels=c("Consortium", "Alternative"))) %>% 
  count(consensus, diagnosis, sort = T) %>%
  group_by(consensus) %>% 
  mutate(freq = n / sum(n)) %>% 
  slice_max(n, n = 25) %>% 
  mutate(grp_diagnosis = sprintf("%s_%s", consensus, diagnosis)) %>% 
  mutate(grp_diagnosis = fct_reorder(grp_diagnosis, n)) %>% 
  {
  ggplot(data = ., aes(x = grp_diagnosis, y = freq)) +
    geom_bar(stat = "identity", width=0.8) +
    facet_wrap( ~ consensus, scales = "free_y") +
    theme_bw() +
    coord_flip() +
    labs(x = "", y = "Frequency") +
    theme(axis.text.x = element_text(angle = 90))+
    ylim(0,0.1) +
    scale_x_discrete(breaks = .$grp_diagnosis, labels = .$diagnosis)
  }
plt_top_25
ggsave(here("figures/2_top_25_diagnoses.pdf"), plot=plt_top_25, width = 7.4, height = 4)
```

```{r, fig.width=3.5, fig.height=2.5}
plt_rank_abundance <- df_cs %>% 
  filter(rank <= 100) %>% 
  mutate(consensus = factor(ifelse(consensus == "consensus1", "Consortium", "Alternative"), 
                            levels=c("Consortium", "Alternative"))) %>% 
  ggplot(aes(x = rank, y = freq, color = factor(consensus)))+
    geom_line() +
    theme_classic()+
    scale_color_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Diagnosis rank", y = "Diagnosis frequency", color = "") +
  theme(
  legend.position = c(0.8, 0.9),
  legend.text = element_text(size = 10),
  legend.background = element_rect(fill=alpha("white",0.5)),
  legend.title = element_blank())

plt_rank_abundance
ggsave(here("figures/S_rank_abundance.pdf"), plot=plt_rank_abundance, width = 3.5, height = 2.5)
```

