---
title: "Diagnosis network analysis"
output: 
  html_notebook:
    toc: True
    toc_depth: 3
    toc_float: True
---

# Setup

```{r}
library(here)
library(tidyverse)
library(igraph)
library(tidygraph)
library(ggraph)

source(here("util_functions.R"))
```

```{r}
source("util_functions.R")

custom_heatmap <- function(data, title, metric, color_scale = hcl.colors(3, "Earth"), midpoint = NULL, symmetric = T){
  scale_max <- ifelse(symmetric,max(abs(data)),max(data))
  scale_min <- ifelse(symmetric,-max(abs(data)),min(data))
  scale_mid <- scale_min + (scale_max - scale_min)/2
  
  midpoint <- ifelse(is.null(midpoint), scale_mid, midpoint)
  
  color_function <-circlize::colorRamp2(c(scale_min,midpoint,scale_max), color_scale)
  
  ComplexHeatmap::Heatmap(
    data,
    col = color_function,
    rect_gp = grid::gpar(col = "black", lwd = 1),
    column_title = title,
    name = metric
  )
}
# custom_heatmap(cor(t(df_count_top_codiag), method = "pearson"), title = "Count top codiag\nAbsolute count", metric = "Pearson\ncorrelation")
```


# Prepare data

```{r}
df <- read_csv(here("data/compiled_all_chatgpt_diagnoses.csv"))

df_codiag <- df %>% 
  mutate(criteria = factor(criteria, levels = c("mcas_consortium", "mcas_alternative", "eular_acr_sle", "slicc_sle"))) %>% 
  filter(grepl("mcas|sle", criteria)) %>% 
  group_by(file, criteria, iteration) %>% 
  nest() %>% 
  mutate(len = map_dbl(data, nrow)) %>% 
  filter(len > 2) %>% 
  mutate(data = map(data, function(x) {
    try(as.data.frame(t(combn(sort(x$diagnosis), 2))))
  })) %>% 
  unnest(data) %>% 
  ungroup() %>% 
  count(criteria, V1, V2, sort = T) %>% 
  filter(V1 != V2) %>% 
  # Ensure that same V1, V2, order is used
  rowwise() %>% 
  mutate(from = min(V1, V2), to = max(V1, V2)) %>% 
  ungroup() %>% 
  group_by(criteria, from, to) %>% 
  summarise(n = sum(n)) %>% 
  # Add some statistics
  group_by(criteria) %>%
  arrange(desc(n), .by_group = T) %>% 
  mutate(rank = 1:n())  %>% 
  mutate(freq = n/sum(n)) %>%
  select(from, to, n, criteria, rank, freq)

df_codiag
```

# Build network graph

```{r}
top_n <-  100

make_mcas_graph <- function(df){
  df %>% 
    as_tbl_graph() %>% 
    activate(edges) %>% 
    mutate(criteria = factor(criteria, levels = c("mcas_consortium", "mcas_alternative", "eular_acr_sle", "slicc_sle")))
}

g_top_codiags <- df_codiag %>% 
  filter(rank <= top_n) %>%
  make_mcas_graph()

g_all_codiags <- df_codiag %>% 
  make_mcas_graph()
```

```{r}
set.seed(1)
ggraph(g_top_codiags, layout = 'fr') + 
    geom_edge_link(alpha = 0.5) +
    geom_node_point(size = 1) +
  facet_wrap(~criteria) +
  theme_void() +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1))
```

### Color by rank

```{r}
df_diagnoses <- read_csv(here("data/compiled_all_chatgpt_diagnoses.csv"))
df_diagnoses <- df_diagnoses %>% 
  filter(criteria %in% c("mcas_consortium", "mcas_alternative", "slicc_sle", "eular_acr_sle")) %>% 
  count(criteria, diagnosis, sort = T) %>% 
  group_by(criteria) %>% 
  mutate(rank = 1:n()) %>% 
  # mutate(criteria = case_when(criteria == "mcas_1" ~ "consensus1", criteria == "mcas_2" ~ "consensus2", .default = criteria)) %>% 
  select(name = diagnosis, criteria, rank) %>% 
  left_join(enframe(rev(viridis::viridis(100)), "rank", "color"), by = "rank") 
df_diagnoses
```
```{r}
criteria_names <- c(
  "mcas_consortium" = "MCAS Consensus",
  "mcas_alternative" = "MCAS Alternative",
  "eular_acr_sle" = "SLE EULAR-ACR",
  "slicc_sle" = "SLE SLICC")

mcas_labeller <- as_labeller(criteria_names)
```


```{r}
point_size <- 2

g_top_codiags_rank <- g_top_codiags %>%
  activate(nodes) %>% 
  mutate(rank = 1:n()) # Will be replaced, but needed to create a legend

# Create base plot
set.seed(1) # Want seed to be called immediately prior to ggraph
plt <- ggraph(g_top_codiags_rank, layout = 'fr') +
  geom_edge_link(alpha = 0.5) +
  geom_node_point(size = point_size*1.5) +
  geom_node_point(size = point_size, aes(color = rank)) + # Will be replaced, but needed to create a legend
  facet_wrap(~criteria, labeller = mcas_labeller) +
  theme_void() +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
  scale_color_viridis_c(direction = -1, breaks = c(1,25,50,75,100)) +
  guides(color = guide_colorbar(reverse = TRUE)) +
  labs(color = "Rank")
```

```{r, fig.width=8, fig.height=6}
ggraph_color_faceted_nodes(plt, 
                           df_diagnoses, 
                           label_col = "name", 
                           facet_col = "criteria",
                           color_col = "color")
```

### Color by centrality


```{r}
point_size <- 2

g_top_codiags_ce <- g_top_codiags %>%
  activate(nodes) %>% 
  mutate(ce = centrality_eigen()) # Will be replaced by needed to create a legend

# Create base plot
set.seed(1)
plt <- ggraph(g_top_codiags_ce, layout = 'fr', ) +
  geom_edge_link(alpha = 0.5) +
  geom_node_point(size = point_size*1.5) +
  geom_node_point(size = point_size, aes(color = ce)) + # Will change, but need to create a legend
  facet_wrap(~criteria, labeller = mcas_labeller) +
  theme_void() +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
  scale_color_viridis_c(breaks = c(0.00,0.25,0.50,0.75,1.00), limits = c(0,1)) +
  labs(color = "Centrality")
```

```{r}
df_diagnoses_centrality <- data.frame(criteria = g_top_codiags_ce %>% activate(edges) %>% pull(criteria) %>% unique()) %>% 
  mutate(sub_graphs = map(criteria, function(c){
    g_top_codiags_ce %>% 
      activate(edges) %>% 
      filter(criteria == c) %>% 
      activate(nodes) %>% 
      mutate(ce = centrality_eigen()) %>% 
      data.frame()
  })) %>% 
  unnest(sub_graphs) 


df_diagnoses_centrality
```

```{r}
map_color <- function(x, min, max, steps){
  df <- data.frame(
    value =  seq(from = min, to = max, length.out = steps)) %>% 
    mutate(color = viridis::viridis(n())) 
  color_index <- findInterval(x, df$value)
  df$color[color_index]
}

df_diagnoses_centrality <- df_diagnoses_centrality %>% 
  mutate(color = map_color(ce, 0,1,100))

df_diagnoses_centrality
```

```{r, fig.width=8, fig.height=6}
ggraph_color_faceted_nodes(plt, 
                           df_diagnoses_centrality, 
                           label_col = "name", 
                           facet_col = "criteria",
                           color_col = "color")
```


### Network density

```{r}
multiple_graph_metrics <- function(x){
  list(
    "total_edges" = gsize(x),
    "total_nodes" = gorder(x),
    "mean_distance" = mean_distance(x),
    "edge_density" = edge_density(x),
    "transitivity" = transitivity(x),
    "reciprocity" = reciprocity(x),
    "edge_connectivity" = edge_connectivity(x),
    "assortativity" = assortativity_degree(x),
    "clique_number" = clique_num(x),
    "clique_count" = count_max_cliques(x),
    "motif_count" = count_motifs(x),
    "diameter" = diameter(x),
    "radius" = radius(x)
  ) %>% 
    enframe(name = "metric", value = "value") %>% 
    unnest(value)
}

get_subgraph_metrics <- function(g){
  data.frame(criteria = g %>% activate(edges) %>% pull(criteria) %>% unique()) %>% 
    mutate(sub_graphs = map(criteria, function(c){
      g %>% as_data_frame() %>% filter(criteria == c) %>% as_tbl_graph(directed = F) %>% multiple_graph_metrics() 
      # g %>% activate(edges) %>% filter(criteria == c) %>% multiple_graph_metrics() 
    })) %>% 
    unnest(sub_graphs) %>% 
    pivot_wider(names_from = "metric", values_from = "value")
}

df_graph_density <- get_subgraph_metrics(g_all_codiags) 
df_graph_density

# **mean_distance - mean distance between all pairs of nodes
# **edge_density - ratio of actual number of edges relative to largest possible number of edges
# transitivity - probability that adjacent vertices are connected (a.k.a. clustering coefficient). Ratio of observed closed triplets to maximum number of closed triplets. https://transportgeography.org/contents/methods/graph-theory-measures-indices/transitivity-graph/
# reciprocity - proportion of mutual connections (i.e. connection in both directions). Requires graph be directed. 
# edge_connectivity - for pair of nodes, number of edges needed to remove all connections, for graph, the lowest edge_connectivity of all node pairs in graph
# assortativity - whether nodes tend to be connected to similar nodes, in this case based on node degree (i.e. are highly connected nodes connected to other highly connected nodes)
# clique_number - size of largest clique
# clique_count - number of cliques of any size (smallest size is of two nodes)
# eccentricity - the distance between a given node and its furthest away node
# diameter - the distance between the two furthest nodes (i.e. the eccentricity of the node with the highest eccentricity)
# center node - nodes with the lowest eccentricity
# radius - maximal distance from the central node(s) to the furthest node
```
```{r, fig.width=4, fig.height=4}
metrics_std <- get_subgraph_metrics(g_top_codiags) %>% 
  column_to_rownames("criteria") %>% 
  vegan::decostand(method = "standardize", MARGIN = 2)
metrics_std[,apply(metrics_std, 2, function(x) !all(is.na(x)))] %>% t() %>% 
  custom_heatmap(title = "Top n co-diagnoses", metric = "Std score")

metrics_std <- get_subgraph_metrics(g_all_codiags) %>% 
  column_to_rownames("criteria") %>% 
  vegan::decostand(method = "standardize", MARGIN = 2)
metrics_std[,apply(metrics_std, 2, function(x) !all(is.na(x)))] %>% t() %>% 
  custom_heatmap(title = "All co-diagnoses", metric = "Std score")
```


```{r}
boot_graph_ci <- function(g, B, seed=NULL){
  if (!is.null(seed)){set.seed(seed)}
  g <- as_adjacency_matrix(g)  
  g <- as.matrix(g) 
  g <- vertboot(g, boot_rep = B)
  g <- sapply(1:B, function(x) edge_density(graph_from_adjacency_matrix(g[[x]])))
  quantile(g, c(0.025, 0.5, 0.975))
}

# boot_graph_ci(graph_from_data_frame(df_codiag), B=10, seed=1234)

# df_density <- df_codiag %>% 
#   ungroup() %>% 
#   select(criteria, from, to, weight = n, rank) %>% 
#   group_by(criteria) %>% 
#   nest() %>% 
#   mutate(boot = map(data, function(g){
#     g <-  graph_from_data_frame(g, directed = F)
#     out <- boot_graph_ci(g, B=5000, seed=1234)
#     out["edge_density"] = edge_density(g)
#     out
#   })) %>% 
#   select(-data) %>% 
#   unnest_wider(boot)

# write_csv(df_density, here("data/edge_density_bootstrap.csv"))

df_density <- read_csv(here("data/edge_density_bootstrap.csv"))
df_density
```
```{r, fig.width = 3.5, fig.height = 3.5}
df_density %>% 
  ggplot(aes(x = criteria))+
  geom_point(aes(y=edge_density))+
  geom_errorbar(aes(ymin = `2.5%`, ymax = `97.5%`), width = 0.4)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x="", y="Edge density")
```


# Subgraph similarity

### Count of co-diagnoses
```{r}
# input_data <- "freq"
input_data <- "rank"

pivot_function <- function(x, data_type, top_n = NA){
  if(data_type == "freq") {return(x)}
  if(data_type == "rank") {
    return(top_n - x + 1)
    }
}

count_connections <- function(g){
  g %>% 
    activate(edges) %>% 
    data.frame() %>% 
    unite(connection, from, to, sep = "_") %>% 
    select(criteria, c(input_data), connection) %>% 
    pivot_wider(names_from = "connection", values_from = input_data, values_fn = function(x) pivot_function(x, data_type = input_data, top_n = top_n), values_fill = 0) %>% 
    column_to_rownames("criteria")
}

df_count_top_codiag <- count_connections(g_top_codiags)
df_count_all_codiag <- count_connections(g_all_codiags)
```

```{r, fig.height=3, fig.width=16}
ComplexHeatmap::Heatmap(df_count_top_codiag, col = viridis::viridis(100))
# ComplexHeatmap::Heatmap(df_count_all_codiag, col = viridis::viridis(100))
```

```{r, fig.width=4, fig.height=3.5}
custom_heatmap(cor(t(df_count_top_codiag), method = "pearson"), title = "Count top codiag\nAbsolute count", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(df_count_top_codiag), method = "spearman"), title = "Count top codiag\nAbsolute count", metric = "Spearman\ncorrelation")
custom_heatmap(cor(t(df_count_all_codiag), method = "pearson"), title = "Count all codiag\nAbsolute count", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(df_count_all_codiag), method = "pearson"), title = "Count all codiag\nAbsolute count", metric = "Spearman\ncorrelation")
```

```{r, fig.width=4, fig.height=3.5}
convert_to_presence_absence <- function(df){
  df %>% 
    rownames_to_column("criteria") %>% 
    pivot_longer(-criteria, names_to = "edge", values_to = "value") %>% 
    drop_na() %>% 
    mutate(value = ifelse(value > 0, 1, 0)) %>% 
    pivot_wider(names_from = "edge", values_from = "value", values_fill = 0) %>% 
    column_to_rownames("criteria")
}


# Removing scale of connections and just using presence or absence
custom_heatmap(cor(t(convert_to_presence_absence(df_count_top_codiag)), method = "pearson"), title = "Count top codiag\nPresence/absence", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(convert_to_presence_absence(df_count_top_codiag)), method = "spearman"), title = "Count top codiag\nPresence/absence", metric = "Spearman\ncorrelation")
custom_heatmap(cor(t(convert_to_presence_absence(df_count_all_codiag)), method = "pearson"), title = "Count all codiag\nPresence/absence", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(convert_to_presence_absence(df_count_all_codiag)), method = "pearson"), title = "Count all codiag\nPresence/absence", metric = "Spearman\ncorrelation")

# Note that converting to presence/absence negates difference between pearson and spearman (because no more differences in rank)
```

### Based on centrality

```{r}
calculate_subgraph_centrality <- function(g, centrality_fun = "centrality_eigen"){
  data.frame(criteria = g %>% activate(edges) %>% pull(criteria) %>% unique()) %>% 
    mutate(sub_graphs = map(criteria, function(c){
      g %>% as_data_frame() %>% filter(criteria == c) %>% as_tbl_graph(directed = F) %>% 
        activate(nodes) %>% mutate(centrality = get(centrality_fun)()) %>% data.frame()
    })) %>% 
  unnest(sub_graphs) %>% 
  pivot_wider(names_from = "name", values_from = "centrality", values_fill = 0) %>% 
  column_to_rownames("criteria")
}

df_centr_top_codiag <- calculate_subgraph_centrality(g_top_codiags)
df_centr_all_codiag <- calculate_subgraph_centrality(g_all_codiags)
```

```{r, fig.width=16, fig.height=4}
custom_heatmap(df_centr_top_codiag, color_scale = viridis::viridis(3), title = "Centrality of top n diagnoses", metric = "Eigenvalue\ncentrality", symmetric = F)
```

```{r, fig.width=4, fig.height=3.5}
custom_heatmap(cor(t(df_centr_top_codiag), method = "pearson"), title = "Top diagnosis centrality", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(df_centr_top_codiag), method = "spearman"), title = "Top diagnosis centrality", metric = "Spearman\ncorrelation")
custom_heatmap(cor(t(df_centr_all_codiag), method = "pearson"), title = "All diagnosis centrality", metric = "Pearson\ncorrelation")
custom_heatmap(cor(t(df_centr_all_codiag), method = "pearson"), title = "All diagnosis centrality", metric = "Spearman\ncorrelation")
```
```{r, fig.width=4, fig.height=3.5}
custom_heatmap(lsa::cosine(t(as.matrix(df_centr_top_codiag))), color_scale = viridis::viridis(3), title = "Top diagnosis centrality", metric = "Cosine\nsimilarity", symmetric = F)
custom_heatmap(lsa::cosine(t(as.matrix(df_centr_all_codiag))), color_scale = viridis::viridis(3), title = "All diagnosis centrality", metric = "Cosine\nsimilarity", symmetric = F)
```

# Find mast cell activation in network

```{r}
mastocytosis_patterns <- c("mastocytosis", "systemic mastocytosis", "aerial mastocytosis", "cutaneous mastocytosis")
mcas_patterns <- c("mast cell activation syndrome", "mast cell activation disorder")

df_codiag %>% 
  mutate_at(vars(c(from, to)), ~ifelse(. %in% mastocytosis_patterns, "mastocytosis", .)) %>% 
  mutate_at(vars(c(from, to)), ~ifelse(. %in% mcas_patterns, "mast cell activation syndrome", .)) %>% 
  group_by(criteria, from, to) %>% 
  summarise(n = sum(n)) %>% 
  group_by(criteria) %>% 
  nest() %>% 
  mutate(data = map(data, function(df){
      as_tbl_graph(df, directed = F) %>% 
        activate(nodes) %>% mutate(centrality = centrality_eigen()) %>% data.frame()
    })) %>% 
  unnest(data) %>% 
  filter(name %in% c(mastocytosis_patterns, mcas_patterns)) %>% 
  pivot_wider(names_from = "name", values_from = "centrality", values_fill = 0) 
```

```{r, fig.width=8, fig.height=6}
# point_size
set.seed(1) # Want seed to be called immediately prior to ggraph
g_top_codiags_rank %>% activate(nodes) %>% mutate(color = ifelse(name == "mastocytosis", "red", "black")) %>% 
ggraph(layout = 'fr') +
  geom_edge_link(alpha = 0.5) +
  geom_node_point(aes(color = color), size = point_size*1.5) + # Will be replaced, but needed to create a legend
  geom_node_point(size = point_size) +
  # facet_wrap(~criteria) +
  # facet_wrap(~criteria, labeller = as_labeller(criteria_names)) +
    facet_wrap(~criteria, labeller = function(x) list(criteria = c("mcas_consortium", "mcas_alternative", "eular_acr_sle", "slicc_sle"))) +
  theme_void() +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
  scale_color_identity()+
  guides(color = guide_colorbar(reverse = TRUE)) +
  labs(color = "Rank")
```

# Final plots

```{r}
points_to_inches(397)
```
```{r, fig.width=4, fig.height=4}
metrics <- get_subgraph_metrics(g_all_codiags) %>% 
  column_to_rownames("criteria") 

metrics_std <- vegan::decostand(metrics, method = "standardize", MARGIN = 2)

rownames(metrics_std) <- case_when( 
  rownames(metrics_std) == "mcas_consortium" ~ "MCAS Consortium",
  rownames(metrics_std) == "mcas_alternative" ~ "MCAS Alternative",
  rownames(metrics_std) == "eular_acr_sle" ~ "SLE EULAR-ACR",
  rownames(metrics_std) == "slicc_sle" ~ "SLE SLICC",
  .default = NA)

rename_metrics <- function(x){
  x <- gsub("_", " ", x)
  str_to_sentence(x)
}

colnames(metrics_std) <-rename_metrics(colnames(metrics_std))

include <- c("Transitivity", "Edge connectivity", "Edge density", "Mean distance",
             "Assortativity", "Diameter", "Radius")

metrics_std <- metrics_std[, colnames(metrics_std) %in% include]

metrics_std <- metrics_std[,apply(metrics_std, 2, function(x) !all(is.na(x)))]

custom_heatmap(t(metrics_std), title = "All co-diagnoses", metric = "Standardized\nscore")
```


```{r, fig.width=3.5, fig.height=8}
criteria_names <- c(
  "mcas_consortium" = "MCAS Consensus",
  "mcas_alternative" = "MCAS Alternative",
  "eular_acr_sle" = "SLE EULAR-ACR",
  "slicc_sle" = "SLE SLICC")


point_size <- 1
set.seed(1)
plt_network <- ggraph(g_top_codiags_ce, layout = 'fr', ) +
  geom_edge_link(alpha = 1, width = 0.25) +
  geom_node_point(size = point_size*1.5) +
  geom_node_point(size = point_size, aes(color = ce)) + # Will change, but need to create a legend
    facet_wrap(~criteria, labeller = mcas_labeller) +
  theme_void() +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
  scale_color_viridis_c(breaks = c(0.00,0.25,0.50,0.75,1.00), limits = c(0,1)) +
  labs(color = "Centrality")
plt_network <- ggraph_color_faceted_nodes(
    plt = plt_network,
    df_diagnoses_centrality,
    label_col = "name",
    facet_col = "criteria",
    color_col = "color"
  )

plt_heatmap <- lsa::cosine(t(as.matrix(df_centr_all_codiag))) %>% 
  {rownames(.) <- criteria_names[rownames(.)];.} %>% 
  {colnames(.) <- criteria_names[colnames(.)];.} %>% 
  custom_heatmap(data = ., color_scale = viridis::viridis(3), title = "", metric = "Cosine\nsimilarity", symmetric = F) %>% 
  ggplotify::as.ggplot()


plt_density <- df_density %>% 
  mutate(criteria = map_chr(criteria, ~criteria_names[.])) %>% 
  ggplot(aes(x = criteria))+
  geom_point(aes(y=edge_density))+
  geom_errorbar(aes(ymin = `2.5%`, ymax = `97.5%`), width = 0.4)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x="", y="Edge density")

plt_figure <- cowplot::plot_grid(
  plt_network,
  # NULL,
  # cowplot::plot_grid(NULL, plt_heatmap,NULL,nrow = 1, rel_widths = c(0.1,0.6,0.1)),
  plt_heatmap,
  cowplot::plot_grid(
    NULL,
    plt_density,
    NULL,
    nrow = 1,
    rel_widths = c(1,8,1)
  ),
  rel_heights =  c(4,4.2,4),
  ncol = 1,
  align = "v"
)

plt_figure
```
```{r}
ggsave(here("figures/4_network.pdf"), plot=plt_figure, width = 3.5, height = 8)
```



# References

https://rpubs.com/pjmurphy/308024

# Permutation

```{r, fig.width=4, fig.height=4}
g_all_codiags <- df_codiag %>% 
  as_tbl_graph()

metrics <- get_subgraph_metrics(g_all_codiags) %>% 
  column_to_rownames("criteria") 

metrics_std <- vegan::decostand(metrics, method = "standardize", MARGIN = 2)

rownames(metrics_std) <- case_when( 
  rownames(metrics_std) == "consensus1" ~ "Consortium MCAS",
  rownames(metrics_std) == "consensus2" ~ "Alternative MCAS",
  rownames(metrics_std) == "eular_acr_sle" ~ "EULAR-ACR SLE",
  rownames(metrics_std) == "slicc_sle" ~ "SLICC SLE",
  .default = NA)

rename_metrics <- function(x){
  x <- gsub("_", " ", x)
  str_to_sentence(x)
}

colnames(metrics_std) <-rename_metrics(colnames(metrics_std))

include <- c("Transitivity", "Edge connectivity", "Edge density", "Mean distance",
             "Assortativity", "Diameter", "Radius")

metrics_std <- metrics_std[, colnames(metrics_std) %in% include]

metrics_std <- metrics_std[,apply(metrics_std, 2, function(x) !all(is.na(x)))]

custom_heatmap(t(metrics_std), title = "All co-diagnoses", metric = "Standardized\nscore")
```
```{r}
df_codiag_expanded <- bind_rows(
df_mcas %>% 
  rename(criteria = consensus) %>% 
  group_by(file, criteria, iteration) %>% 
  nest() %>% 
  mutate(len = map_dbl(data, nrow)) %>% 
  filter(len > 2) %>% 
  mutate(data = map(data, function(x) {
    try(as.data.frame(t(combn(sort(x$diagnosis), 2))))
  })) %>% 
  unnest(data) %>% 
  ungroup(),

df_sle %>% 
  group_by(file, criteria, iteration) %>% 
  nest() %>% 
  mutate(len = map_dbl(data, nrow)) %>% 
  filter(len > 2) %>% 
  mutate(data = map(data, function(x) {
    try(as.data.frame(t(combn(sort(x$diagnosis), 2))))
  })) %>% 
  unnest(data) %>% 
  ungroup()
) %>% 
  select(criteria, V1, V2)

df_codiag_expanded
```

```{r, fig.width=4, fig.height=4}
g_all_codiags_permute <- df_codiag_expanded %>% 
  mutate(criteria = sample(criteria)) %>% 
  count(criteria, V1, V2, sort = T) %>% 
  filter(V1 != V2) %>% 
  # Ensure that same V1, V2, order is used
  rowwise() %>% 
  mutate(from = min(V1, V2), to = max(V1, V2)) %>% 
  ungroup() %>% 
  group_by(criteria, from, to) %>% 
  summarise(n = sum(n)) %>% 
  # Add some statistics
  # group_by(criteria) %>%
  # arrange(desc(n), .by_group = T) %>% 
  # mutate(rank = 1:n())  %>% 
  # mutate(freq = n/sum(n)) %>%
  select(from, to, n, criteria) %>% 
  as_tbl_graph()

metrics_permute <- get_subgraph_metrics(g_all_codiags_permute) %>% 
  column_to_rownames("criteria") 

metrics
metrics_permute
metrics/metrics_permute

metrics_std_permute <- vegan::decostand(metrics_permute, method = "standardize", MARGIN = 2)

rownames(metrics_std_permute) <- case_when( 
  rownames(metrics_std_permute) == "consensus1" ~ "Consortium MCAS",
  rownames(metrics_std_permute) == "consensus2" ~ "Alternative MCAS",
  rownames(metrics_std_permute) == "eular_acr_sle" ~ "EULAR-ACR SLE",
  rownames(metrics_std_permute) == "slicc_sle" ~ "SLICC SLE",
  .default = NA)

rename_metrics <- function(x){
  x <- gsub("_", " ", x)
  str_to_sentence(x)
}

colnames(metrics_std_permute) <-rename_metrics(colnames(metrics_std_permute))

include <- c("Transitivity", "Edge connectivity", "Edge density", "Mean distance",
             "Assortativity", "Diameter", "Radius")

metrics_std_permute <- metrics_std_permute[, colnames(metrics_std_permute) %in% include]

metrics_std_permute <- metrics_std_permute[,apply(metrics_std_permute, 2, function(x) !all(is.na(x)))]

custom_heatmap(t(metrics_std_permute), title = "All co-diagnoses", metric = "Standardized\nscore")
```


```{r}
df_original_graph <- tibble(
  codiagnosis_selection = c("top", "all"),
  data = list(
  get_subgraph_metrics(g_top_codiags),
  get_subgraph_metrics(g_all_codiags)
  )
) %>% 
  unnest(data) %>% 
  mutate(criteria = ifelse(criteria == "consensus1", "mcas_consortium", criteria)) %>% 
  mutate(criteria = ifelse(criteria == "consensus2", "mcas_alternative", criteria))
df_original_graph
```
```{r}
df_original_graph_diff <- tibble(codiagnosis_selection=c("top","all")) %>% 
  mutate(data = list(as.tibble(t(combn(sort(unique(df_original_graph$criteria)), 2))))) %>% 
  unnest(data) %>% 
  left_join(
    df_original_graph %>% 
      pivot_longer(!c(codiagnosis_selection, criteria), names_to = "metric", values_to = "value"),
    by = c("V1" = "criteria", "codiagnosis_selection")
  ) %>% 
  left_join(
    df_original_graph %>% 
      pivot_longer(!c(codiagnosis_selection, criteria), names_to = "metric", values_to = "value"),
    by = c("V2" = "criteria", "codiagnosis_selection")
  ) %>% 
  filter(metric.x == metric.y) %>% 
  mutate(value = abs(value.x-value.y), metric = metric.x) %>% 
  unite(comp, V1, V2) %>% 
  select(!contains(c(".x", ".y"))) %>% 
  pivot_wider(names_from = "metric", values_from = "value")
df_original_graph_diff
```


```{r, fig.height = 4, fig.width=12}
variable <- "edge_density"

df_permute_graph <- bind_rows(
  read_csv(here("data/null_permute_network_slurm_231215_221551.csv")) %>% mutate(codiagnosis_selection = "all"),
  read_csv(here("data/null_permute_top_network_slurm_231216_113453.csv")) %>% mutate(codiagnosis_selection  = "top")
)
df_permute_graph %>% 
  unite(comp, V1, V2) %>% 
  filter(!grepl("kawasaki|migraine", comp)) %>% 
  ggplot(aes(x = !!sym(variable)))+
  # geom_histogram(aes(y=..density..))+
  geom_histogram()+
  geom_vline(data = df_original_graph_diff, aes(xintercept = !!sym(variable)), color = "red")+
  facet_wrap(comp~codiagnosis_selection, scales = "free", nrow = 2)+
  theme_bw()
```

```{r}
df_original_graph %>% 
  pivot_longer(-criteria, names_to = "metric", values_to = "value") %>% 
  filter(metric %in% c("edge_density", "mean_distance")) %>% 
  ggplot(aes(x = criteria, y = value))+
  geom_bar(stat = "identity")+
  facet_wrap(~metric, scales = "free_y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45, hjust = 1))
```
```{r}

```


```{r}
df_permute_graph %>% 
  unite(comp, V1, V2, sep = ".") %>% 
  filter(!grepl("kawasaki|migraine", comp)) %>% 
  group_by(comp) %>% 
  summarise(min(edge_density), median(edge_density), max(edge_density))
```

```{r}
df_original_graph <- tibble(
  codiagnosis_selection = c("top", "all"),
  data = list(
  get_subgraph_metrics(g_top_codiags),
  get_subgraph_metrics(g_all_codiags)
  )
) %>% 
  unnest(data) %>% 
  mutate(criteria = ifelse(criteria == "consensus1", "mcas_consortium", criteria)) %>% 
  mutate(criteria = ifelse(criteria == "consensus2", "mcas_alternative", criteria))
df_original_graph
```

```{r, fig.width=4, fig.height=4}
criteria_order <- c("mcas_consortium", "mcas_alternative", "eular_acr_sle", "slicc_sle")

df_original_graph %>% 
  mutate(criteria = factor(criteria, levels = criteria_order)) %>% 
  ggplot(aes(x = criteria, y = edge_density))+
  geom_bar(stat = "identity", color = "black")+
  facet_wrap(~codiagnosis_selection, scales = "free_y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  labs(x = "")
```

```{r}
df_permute_graph %>% 
  count(codiagnosis_selection, iteration) %>% 
  count(codiagnosis_selection)
```

