---
title: "R Notebook"
output: html_notebook
---

```{r}
# library(pubmedR)
# library(RISmed)
library(here)
library(tidyverse)
library(easyPubMed)
library(igraph)
library(visNetwork)
library(RColorBrewer)
```

```{r}
api_key <- "a1a1f2d88b6d673607fd35fc11695285fd08"
```

```{r}
res <- RISmed::EUtilsSummary("copd", type="esearch", db="pubmed", datetype='pdat', retmax=500)
```

```{r}
x <- RISmed::EUtilsGet("27671109")
```

```{r}
x <- easyPubMed::get_pubmed_ids("27671109[pmid]")
xml2::read_xml(articles_to_list(fetch_pubmed_data(x, format = "xml")))
RISmed::fetch_pubmed_data(x, format = "xml")
RISmed::custom_grep(fetch_pubmed_data(x, format = "xml"), tag = "PubDate")
```

```{r}
get_cite_pmids <- function(pmid){
  path <- sprintf("https://pubmed.ncbi.nlm.nih.gov/?format=pmid&linkname=pubmed_pubmed_citedin&size=200&from_uid=%s",pmid)
  rvest::read_html(path) %>% 
    rvest::html_elements("pre") %>% 
    rvest::html_text2() %>% 
    str_split(., "\\\r\\\n") %>% 
    unlist()
}

get_cite_pmids("27671109")
get_cite_pmids("32324159")
```

https://www.biostars.org/p/4251/#5878


https://pypi.org/project/pmidcite/
icite -H; icite 26032263 --load_citations | sort -k6 -r

Or got to PMID citation page and click save as a csv

```{r}
file_path <- here("data/mcas_citations")
```

# Number of citations for consensus-related publications

```{r}
df <- tibble(file = list.files(sprintf("%s/citation_lists/",file_path), full.names = T)) %>% 
  mutate(pmid = gsub("[a-zA-Z]|[[:punct:]]","",file)) %>% 
  mutate(data = map(file, function(x){
    read_csv(x) %>% 
      count(`Publication Year`) %>% 
      mutate(cum_n = cumsum(n))
  })) %>% 
  select(-file) %>% 
  unnest(data) 

df_2 <- read_csv(sprintf("%s/pmid_key.csv", file_path), col_types = c("c")) %>% 
  right_join(df, by= "pmid") %>% 
  mutate(consensus = sprintf("Consensus-%s",consensus)) %>% 
  group_by(consensus, `Publication Year`) %>% 
  summarise(n = sum(n)) %>% 
  group_by(consensus) %>% 
  mutate(cum_n = cumsum(n))

df_3 <- read_csv(sprintf("%s/pmid_key.csv", file_path), col_types = c("c")) %>% 
  right_join(df, by= "pmid") %>% 
  mutate(consensus = sprintf("Consensus-%s",consensus))

df_4 <- df_2 %>% 
  mutate(pmid = "total")


df_3 %>% 
  # ggplot(aes(x = `Publication Year`, y = n, color = pmid))+
  ggplot(aes(x = `Publication Year`, y = cum_n, group = pmid, color = consensus))+
  geom_path(alpha = 0.5, linetype = "dashed")+
  geom_path(data = df_4, aes(group = consensus))+
  theme_classic() +
  scale_color_brewer(palette = "Set1")
```

# Authors

```{r}
make_author_df <- function(pmid){
  query <- sprintf("%s[pmid]", pmid)
  xml_record <- fetch_pubmed_data(get_pubmed_ids(query), format = "xml") 
  # xml_record
  data.frame(
    first = custom_grep(xml_record, tag = "ForeName", format = "char"),
    last = custom_grep(xml_record, tag = "LastName", format = "char")
  )
}

make_author_df("22041891")
```

```{r}
df_consensus_author_tally <- read_csv("pmid_key.csv", col_types = c("c")) %>% 
  mutate(data = map(pmid, make_author_df)) %>% 
  unnest(data)

df_consensus_author_tally
```

```{r}
df_consensus_author_tally %>% 
  count(consensus, last, sort = T) %>% 
  group_by(consensus) %>% 
  top_n(5, n) %>% 
  filter(n!=1) %>% 
  mutate(last = fct_reorder(last, n)) %>% 
  mutate(consensus = sprintf("Consensus-%s",consensus)) %>% 
  ggplot(aes(x = last, y = n))+
  geom_bar(stat = "identity") +
  theme_bw()+
  coord_flip() +
  facet_wrap(~consensus, scale = "free")
```

# Publication network analysis

```{r}
# Get all info for all publications related to MCAS
mcas_query <- get_pubmed_ids("'mast cell activation syndrome'")
mcas_xml <- fetch_pubmed_data(mcas_query, format = "xml")
mcas_list <- articles_to_list(mcas_xml)
```

```{r}
# Function to isolate names of all authors from a publication's xml data
get_authors <- function(xml){
  article_to_df(xml) %>%
    mutate(name = sprintf("%s %s", firstname, lastname)) %>%
    select(name)
}
get_authors(mcas_list[[1]])
```

```{r}
# # Function to Make list of all pairs of MCAS authors who published together 
# ### Todo, this duplicates some code from chunk above. Can simplify
# make_author_pairs <- function(xml){
#   article_to_df(xml) %>% 
#   mutate(name = sprintf("%s %s", firstname, lastname)) %>% 
#   pull(name) %>% 
#   expand_grid(author_1 = ., author_2 = .)
# }
# make_author_pairs(mcas_list[[1]])
```

```{r}
# df_author
# g <- graph_from_data_frame(df_author, directed = F)
# plot(g)
```
```{r}
author_list <- map(mcas_list, get_authors)
```
```{r}
df_author_count <- author_list %>% 
  do.call(rbind, . ) %>% 
  count(name, sort = T)
df_author_count
```

```{r}
# Tally up all co-author pairs
df_coauthor_tally <- map(author_list, ~expand_grid(author_1 = .$name, author_2 = .$name)) %>% 
  do.call(rbind, .) %>% 
  group_by(author_1, author_2) %>% 
  tally(sort = T)

df_coauthor_tally


```

```{r}
# Create undirected graph of all co-author pairs
g <- df_coauthor_tally %>% 
  filter(author_1 != author_2) %>% 
  filter(n >= 2) %>% 
  graph_from_data_frame(directed = F)
```





```{r}
# df.g <- igraph::as_data_frame(g, what = "both")
```

```{r}
g <- df_coauthor_tally %>% 
  filter(author_1 != author_2) %>% 
  filter(n >= 2) %>% 
  graph_from_data_frame(directed = F)
df.g <- igraph::as_data_frame(g, what = "both")
df.g
```

```{r}
# Assign color spectrum to authors based on number of publications
n_colors <- 10
my_palette <- colorRampPalette(viridisLite::viridis(11))(n = n_colors)
df.v <- df_author_count %>% 
  mutate(color = cut(n, 10, labels = my_palette))
df.v
```

```{r}
# Assign colors above to vertices
df.g$vertices <- df.g$vertices %>% left_join(df.v %>% select(-n), by="name")
```

```{r, fig.width=12, fig.height=8}
g <- graph_from_data_frame(df.g$edges, directed = F, vertices = df.g$vertices)
visIgraph(g) %>% 
    visOptions(highlightNearest = list(enabled = T, hover = T), 
             nodesIdSelection = list(enabled = T, values = sort(V(g)$name)))
```
```{r, fig.width=12, fig.height=8}
visIgraph(g, physics = T) %>% 
    visPhysics(stabilization = T, barnesHut = list(avoidOverlap = 0.25)) %>% 
    visOptions(highlightNearest = list(enabled = T, hover = T), 
             nodesIdSelection = list(enabled = T, values = sort(V(g)$name)))
```

```{r, fig.width=4, fig.height=6}
# Plot list of top MCAS authors
df_author_count %>% 
  mutate(name = fct_reorder(name, n)) %>% 
  top_n(25, n) %>% 
  ggplot(aes(x = name, y = n))+
  geom_bar(stat = "identity")+
  coord_flip()+
  theme_bw() +
  labs(y = "Number of publications", x = "")
```

```{r}
# Facet list of top MCAS authors based on whether they contributed to
# Consensus 1 vs 2
df_consensus_author_tally %>% 
  mutate(name = sprintf("%s %s", first, last)) %>% 
  mutate(consensus = sprintf("Consensus-%s", consensus)) %>% 
  select(name, consensus) %>% 
  distinct() %>% 
  right_join(df_author_count_2) %>% 
  drop_na() %>% 
  mutate(name = fct_reorder(name, n)) %>% 
  group_by(consensus) %>% 
  top_n(10, n) %>% 
  ggplot(aes(x = name, y = n))+
  geom_bar(stat = "identity")+
  coord_flip()+
  theme_bw() +
  labs(y = "Number of publications", x = "") +
  facet_wrap(~consensus, scales = "free")
```

# MCAS publication rate

```{r}
total_cite_plt <- read_csv("csv-mastcellac-set.csv") %>% 
  count(`Publication Year`) %>% 
  mutate(cum_n = cumsum(n)) %>% 
  filter(`Publication Year` != 2023) %>% 
  # ggplot(aes(x = `Publication Year`, y = cum_n))+
  ggplot(aes(x = `Publication Year`, y = n))+
  geom_path()+
  theme_bw() +
  labs(y = "Annual number of publications", x = "")
```

```{r}
relative_cite_plt <- read_csv("csv-mastcellac-set.csv") %>% 
  count(year = `Publication Year`, name = "n_mcas") %>% 
  left_join(read_csv("pmid_entries.csv")) %>% 
  drop_na() %>% 
  mutate(freq = n_mcas/n) %>% 
  ggplot(aes(x = year, y = freq))+
  geom_path()+
  theme_bw() +
  labs(y = "Relative number of publications", x = "")
```
```{r, fig.width=10, fig.height=5}
cowplot::plot_grid(
  total_cite_plt,
  relative_cite_plt,
  nrow = 1
)
```


