---
title: "4_Co-diagnosis network analysis"
output: html_notebook
---

```{r, message = F}
source(here("utils/data_processing.R"))
source(here("utils/figures.R"))
```

# Import and process data
```{r}
df_gpt3 <- process_json(here("data/chatgpt_json_output/gpt-3.5-turbo-1106/"))
df_gpt4 <- process_json(here("data/chatgpt_json_output/gpt-4-turbo-preview/"))
```

```{r}
df_codiag_gpt3 <- create_codiagnosis_df(df_gpt3)
df_codiag_gpt4 <- create_codiagnosis_df(df_gpt4)
```

```{r}
top_n <-  200

graph_200_gpt3 <- make_codiagnosis_graph(df_codiag_gpt3, n_diagnoses = top_n)
graph_200_gpt4 <- make_codiagnosis_graph(df_codiag_gpt4, n_diagnoses = top_n)
```

# Plot graph
```{r, fig.width=8, fig.height=6}
set.seed(1234);centrality_graph(graph_200_gpt3) + ggtitle("GPT3")
set.seed(1234);centrality_graph(graph_200_gpt4) + ggtitle("GPT4")
```

```{r}
boot_graph_ci <- function(g, B, seed=NULL){
  if (!is.null(seed)){set.seed(seed)}
  g <- as_adjacency_matrix(g)  
  g <- as.matrix(g) 
  g <- snowboot::vertboot(g, boot_rep = B)
  g <- sapply(1:B, function(x) edge_density(graph_from_adjacency_matrix(g[[x]])))
  quantile(g, c(0.025, 0.5, 0.975))
}

# boot_graph_ci(graph_from_data_frame(df_codiag), B=10, seed=1234)

df_density <- df_codiag_gpt4 %>%
  ungroup() %>%
  select(criteria, from, to, weight = n, rank) %>%
  group_by(criteria) %>%
  nest() %>%
  mutate(boot = map(data, function(g){
    g <-  graph_from_data_frame(g, directed = F)
    out <- boot_graph_ci(g, B=100, seed=1234)
    out["edge_density"] = edge_density(g)
    out
  })) %>%
  select(-data) %>%
  unnest_wider(boot)

# write_csv(df_density, here("data/edge_density_bootstrap.csv"))

# df_density <- read_csv(here("data/edge_density_bootstrap.csv"))
df_density
```

```{r, fig.width = 3.5, fig.height = 3.5}
df_density %>% 
  format_criteria() %>% 
  ggplot(aes(x = criteria))+
  geom_point(aes(y=`50%`))+
  geom_point(aes(y=edge_density), color = "red")+
  geom_errorbar(aes(ymin = `2.5%`, ymax = `97.5%`), width = 0.4)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x="", y="Edge density")
```
```{r}
calculate_subgraph_centrality <- function(g, centrality_fun = "centrality_eigen"){
  data.frame(criteria = g %>% activate(edges) %>% pull(criteria) %>% unique()) %>% 
    mutate(sub_graphs = map(criteria, function(c){
      g %>% as_data_frame() %>% filter(criteria == c) %>% as_tbl_graph(directed = F) %>% 
        activate(nodes) %>% mutate(centrality = get(centrality_fun)()) %>% data.frame()
    })) %>% 
  unnest(sub_graphs) %>% 
  pivot_wider(names_from = "name", values_from = "centrality", values_fill = 0) %>% 
  column_to_rownames("criteria")
}

graph_all_gpt4 <- make_codiagnosis_graph(df_codiag_gpt4, n_diagnoses = top_n)
df_centr_gpt4 <- calculate_subgraph_centrality(graph_all_gpt4)
```

```{r}
custom_heatmap <- function(data, title, metric, color_scale = hcl.colors(3, "Earth"), midpoint = NULL, symmetric = T){
  scale_max <- ifelse(symmetric,max(abs(data)),max(data))
  scale_min <- ifelse(symmetric,-max(abs(data)),min(data))
  scale_mid <- scale_min + (scale_max - scale_min)/2
  
  midpoint <- ifelse(is.null(midpoint), scale_mid, midpoint)
  
  color_function <-circlize::colorRamp2(c(scale_min,midpoint,scale_max), color_scale)
  
  ComplexHeatmap::Heatmap(
    data,
    col = color_function,
    rect_gp = grid::gpar(col = "black", lwd = 1),
    column_title = title,
    name = metric
  )
}
```


```{r, fig.width=4, fig.height=3.5}
custom_heatmap(lsa::cosine(t(as.matrix(df_centr_gpt4))), color_scale = viridis::viridis(3), title = "diagnosis centrality", metric = "Cosine\nsimilarity", symmetric = F)


# custom_heatmap(lsa::cosine(t(as.matrix(df_centr_all_codiag))), color_scale = viridis::viridis(3), title = "All diagnosis centrality", metric = "Cosine\nsimilarity", symmetric = F)
```



