---
title: "ICD Mapping Table"
output: html_notebook
---

```{r}
library(here)
library(tidyverse)
library(flextable)
source(here("utils/general.R"))
```

```{r, message = F}
read_icd_mapping <- function(model){
  path <- str_glue("data/chatgpt_embeddings/text-embedding-3-small/{model}_diagnoses_chatgpt_embeddings_to_ICD.csv")
  path <- here(path)
  read_csv(path)
}
df_gpt3.5_mapping <- read_icd_mapping("gpt-3.5-turbo-1106")
df_gpt4.0_mapping <- read_icd_mapping("gpt-4-turbo-preview")
df_claude3_haiku_t1.0_mapping <- read_icd_mapping("claude-3-haiku-20240307_t1-0")
df_claude3_opus_t1.0_mapping <- read_icd_mapping("claude-3-opus-20240229_t1-0")
df_gemini1.0_pro_t1.0_mapping <- read_icd_mapping("gemini-1.0-pro-002_t1-0")
df_gemini1.5_pro_t1.0_mapping <- read_icd_mapping("gemini-1.5-pro-001_t1-0")
```


```{r}
embedding_mapping_long <- combine_data_frames(
df_gpt3.5_mapping,
df_gpt4.0_mapping,
df_claude3_haiku_t1.0_mapping,
df_claude3_opus_t1.0_mapping ,
df_gemini1.0_pro_t1.0_mapping,
df_gemini1.5_pro_t1.0_mapping
) %>% 
  unite(ICD_diagnosis, code, diagnosis.y, sep = " ") %>% 
  select(original_diagnosis=diagnosis.x, ICD_diagnosis) %>% 
  distinct()

embedding_mapping_wide <- embedding_mapping_long %>% 
  nest(.by = "ICD_diagnosis") %>% 
  mutate(n = map_dbl(data, nrow)) %>% 
  mutate(data = map_chr(data, ~paste(pull(.),collapse = "  •  ")))
```
```{r}
embedding_mapping_long
```
```{r}
embedding_mapping_wide
```
```{r}
embedding_mapping_wide %>% 
  select(-n) %>% 
  filter(grepl("D47.02 Systemic mastocytosis", ICD_diagnosis)) %>% 
  rename(`ICD diagnosis`=ICD_diagnosis, `Original LLM output`=data) %>% 
  flextable() %>% 
  # width(width = 4) %>% 
  # autofit(part="body") %>% 
  width(j=2,width=5) %>% 
  width(j=1,width=2) %>% 
  fontsize(size = 9) %>% 
  fontsize(size = 10, part = "header") %>% 
  padding(padding = 0) %>% 
  # align(j = 2:3, align = "center", part = "all") %>% 
  set_table_properties(opts_pdf = list(arraystretch = 1.25)) %>% 
  # {print(., preview = "pdf");.}
  {print(., preview = "docx");.}
```
